// Encrypts secrets (AI provider API keys) before they are stored in the
// database, so dumps and backups do not carry them in clear text.
//
// Env: BALAS_SECRET_KEY (generated by setup-vps.sh; 64 hex chars).
import { HttpError } from "./http.ts";

let cachedKey: Promise<CryptoKey> | null = null;

function secretKey(): Promise<CryptoKey> {
  if (!cachedKey) {
    const raw = Deno.env.get("BALAS_SECRET_KEY");
    if (!raw || raw.length < 32) {
      throw new HttpError(500, "BALAS_SECRET_KEY is not configured", "not_configured");
    }
    cachedKey = crypto.subtle
      .digest("SHA-256", new TextEncoder().encode(raw))
      .then((digest) => crypto.subtle.importKey("raw", digest, "AES-GCM", false, ["encrypt", "decrypt"]));
  }
  return cachedKey;
}

const toBase64 = (bytes: Uint8Array) => btoa(String.fromCharCode(...bytes));
const fromBase64 = (text: string) => Uint8Array.from(atob(text), (c) => c.charCodeAt(0));

export async function encryptSecret(plain: string): Promise<string> {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const sealed = new Uint8Array(
    await crypto.subtle.encrypt({ name: "AES-GCM", iv }, await secretKey(), new TextEncoder().encode(plain)),
  );
  const out = new Uint8Array(iv.length + sealed.length);
  out.set(iv);
  out.set(sealed, iv.length);
  return `v1:${toBase64(out)}`;
}

export async function decryptSecret(stored: string): Promise<string> {
  if (!stored.startsWith("v1:")) throw new Error("unknown secret format");
  const data = fromBase64(stored.slice(3));
  try {
    const plain = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: data.slice(0, 12) },
      await secretKey(),
      data.slice(12),
    );
    return new TextDecoder().decode(plain);
  } catch {
    throw new HttpError(500, "API key tidak bisa dibuka (BALAS_SECRET_KEY berubah?). Simpan ulang API key.", "secret_unreadable");
  }
}
