// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdgfyqyeinemllyizesv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZ2Z5cXllaW5lbWxseWl6ZXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDgxMjgsImV4cCI6MjA2NzgyNDEyOH0.F_gQQrFLUqaZ8pLsfRcceB_VGtgvzk86VTy-_ODA7pU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});